Component({
    data:{
        number:0,
    },
    methods:{
        reduceNumber:function(){
            this.setData({
                number:this.data.number-1
            });
            global.WY.trigger('number-select',this.data,this.dataset);
        },
        plusNumber:function(){
            this.setData({
                number:this.data.number+1
            })
            global.WY.trigger('number-select',this.data,this.dataset);
        }
    }
});